/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Negocio.Aluno;
import Negocio.Responsavel;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author ANA
 */
public class TelaAlunoMenor extends javax.swing.JFrame {
    
    private ArrayList<Aluno> listaAluno = new ArrayList<>();

    public TelaAlunoMenor(ArrayList<Aluno> listaAluno){
       initComponents();
       this.listaAluno = listaAluno;
    }

    /**
     /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoTurno = new javax.swing.ButtonGroup();
        jMenu1 = new javax.swing.JMenu();
        tituloTela = new javax.swing.JLabel();
        labelNome = new javax.swing.JLabel();
        campoNome = new javax.swing.JTextField();
        botaoSalvar = new javax.swing.JButton();
        labelEndereco = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        campoEndereco = new javax.swing.JTextArea();
        labelNome1 = new javax.swing.JLabel();
        labelNome2 = new javax.swing.JLabel();
        campoCPF = new javax.swing.JFormattedTextField();
        campoDataIngresso = new javax.swing.JFormattedTextField();
        labelNome3 = new javax.swing.JLabel();
        campoEmail = new javax.swing.JTextField();
        labelEndereco1 = new javax.swing.JLabel();
        campoCelular = new javax.swing.JFormattedTextField();
        checkEstudante = new javax.swing.JCheckBox();
        busca = new javax.swing.JButton();
        tituloTela1 = new javax.swing.JLabel();
        labelNome4 = new javax.swing.JLabel();
        labelNome5 = new javax.swing.JLabel();
        labelNome6 = new javax.swing.JLabel();
        campoCPFResponsavel = new javax.swing.JFormattedTextField();
        campoTelefoneResponsavel = new javax.swing.JFormattedTextField();
        campoNomeResponsavel = new javax.swing.JTextField();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela de Aluno");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tituloTela.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tituloTela.setText("Matricula do aluno menor");

        labelNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelNome.setText("Nome");
        labelNome.setName("nome"); // NOI18N

        campoNome.setName("campoNome"); // NOI18N
        campoNome.setOpaque(true);

        botaoSalvar.setText("Inserir");
        botaoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarActionPerformed(evt);
            }
        });

        labelEndereco.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelEndereco.setText("Endereço");
        labelEndereco.setName("endereco"); // NOI18N

        campoEndereco.setColumns(20);
        campoEndereco.setRows(5);
        campoEndereco.setName("campoEndereco"); // NOI18N
        jScrollPane1.setViewportView(campoEndereco);

        labelNome1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelNome1.setText("CPF");
        labelNome1.setName("cpf"); // NOI18N

        labelNome2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelNome2.setText("Celular");
        labelNome2.setName("cpf"); // NOI18N

        try {
            campoCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campoCPF.setName("campoCpf"); // NOI18N

        try {
            campoDataIngresso.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campoDataIngresso.setToolTipText("");
        campoDataIngresso.setName("campoData"); // NOI18N

        labelNome3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelNome3.setText("E-mail");
        labelNome3.setName("e-mail"); // NOI18N

        campoEmail.setName("campoEmail"); // NOI18N
        campoEmail.setOpaque(true);

        labelEndereco1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelEndereco1.setText("Data ingresso");
        labelEndereco1.setName("dataIngresso"); // NOI18N

        try {
            campoCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campoCelular.setToolTipText("");
        campoCelular.setName("campoCelular"); // NOI18N

        checkEstudante.setText("Estudante");

        busca.setText("Busca");
        busca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscaActionPerformed(evt);
            }
        });

        tituloTela1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tituloTela1.setText("Dados do responsavel");

        labelNome4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelNome4.setText("Nome");
        labelNome4.setName("nome"); // NOI18N

        labelNome5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelNome5.setText("CPF");
        labelNome5.setName("cpf"); // NOI18N

        labelNome6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelNome6.setText("Telefone");
        labelNome6.setName("cpf"); // NOI18N

        try {
            campoCPFResponsavel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campoCPFResponsavel.setName("campoCpf"); // NOI18N

        try {
            campoTelefoneResponsavel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campoTelefoneResponsavel.setToolTipText("");
        campoTelefoneResponsavel.setName("campoCelular"); // NOI18N

        campoNomeResponsavel.setName("campoNome"); // NOI18N
        campoNomeResponsavel.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(218, 218, 218)
                .addComponent(tituloTela)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(289, 289, 289)
                        .addComponent(botaoSalvar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(tituloTela1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelNome3)
                            .addComponent(labelNome))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelNome2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(campoCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelNome1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(campoCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(busca)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelNome5)
                                .addGap(18, 18, 18)
                                .addComponent(campoCPFResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelEndereco)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelEndereco1)
                                        .addGap(18, 18, 18)
                                        .addComponent(campoDataIngresso, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(checkEstudante))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelNome4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoNomeResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelNome6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campoTelefoneResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(161, 161, 161))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(tituloTela)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNome)
                    .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNome1)
                    .addComponent(campoCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(busca, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNome2)
                    .addComponent(labelNome3)
                    .addComponent(campoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelEndereco)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelEndereco1)
                            .addComponent(campoDataIngresso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(checkEstudante)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tituloTela1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNome4)
                    .addComponent(labelNome6)
                    .addComponent(campoTelefoneResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoNomeResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNome5)
                    .addComponent(campoCPFResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(botaoSalvar)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    
    public boolean camposValidos(){
        /*if (textMatricula.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Informe a matricula");
            return false;
        }
        else if (textNome.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Informe o nome do aluno");
            return false;
        }
        else if (opcaoCurso.getSelectedIndex() < 0){
            JOptionPane.showMessageDialog(null, "Informe o curso");
            return false;
        }
        else */ 
            return true;
            
                  
    }
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        /*opcaoCurso.removeAllItems();
        for (Curso c:listaCurso){
            opcaoCurso.addItem(c.getNomeCurso());
        }*/ 
    }//GEN-LAST:event_formWindowOpened

    private void botaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarActionPerformed
        Responsavel responsavel = new Responsavel(campoNomeResponsavel.getText(),campoCPFResponsavel.getText(),campoTelefoneResponsavel.getText());
        Aluno aluno = new Aluno(responsavel,campoCPF.getText(),campoNome.getText(),campoEndereco.getText(),campoEmail.getText(),campoCelular.getText(),campoDataIngresso.getText(),checkEstudante.isSelected());
      
        listaAluno.add(aluno);
        JOptionPane.showMessageDialog(null, "Incluido com sucesso!");
        
        limpar();
    }//GEN-LAST:event_botaoSalvarActionPerformed

    private void buscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscaActionPerformed
        for (int i=0; i< listaAluno.size();i++)
            if (campoCPF.getText().equals(listaAluno.get(i).getCpf()))
            {
                campoNome.setText(listaAluno.get(i).getNome());
                campoEmail.setText(listaAluno.get(i).getEmail());
                campoEndereco.setText(listaAluno.get(i).getEndereco());
                campoCelular.setText(listaAluno.get(i).getCelular());
                campoDataIngresso.setText(listaAluno.get(i).getDataIngresso());
                campoCPFResponsavel.setText(listaAluno.get(i).getResponsavel().getCpf());
                campoNomeResponsavel.setText(listaAluno.get(i).getResponsavel().getNome());
                campoTelefoneResponsavel.setText(listaAluno.get(i).getResponsavel().getTelefone());
            }
        
        
    }//GEN-LAST:event_buscaActionPerformed

    public void limpar(){
        campoNome.setText("");
        campoCPF.setText("");
        campoEmail.setText("");
        campoCelular.setText("");
        campoEndereco.setText("");
        campoDataIngresso.setText("");
        campoCPFResponsavel.setText("");
        campoNomeResponsavel.setText("");
        campoTelefoneResponsavel.setText("");
    }
        
    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoSalvar;
    private javax.swing.JButton busca;
    private javax.swing.JFormattedTextField campoCPF;
    private javax.swing.JFormattedTextField campoCPFResponsavel;
    private javax.swing.JFormattedTextField campoCelular;
    private javax.swing.JFormattedTextField campoDataIngresso;
    private javax.swing.JTextField campoEmail;
    private javax.swing.JTextArea campoEndereco;
    private javax.swing.JTextField campoNome;
    private javax.swing.JTextField campoNomeResponsavel;
    private javax.swing.JFormattedTextField campoTelefoneResponsavel;
    private javax.swing.JCheckBox checkEstudante;
    private javax.swing.ButtonGroup grupoTurno;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelEndereco;
    private javax.swing.JLabel labelEndereco1;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelNome1;
    private javax.swing.JLabel labelNome2;
    private javax.swing.JLabel labelNome3;
    private javax.swing.JLabel labelNome4;
    private javax.swing.JLabel labelNome5;
    private javax.swing.JLabel labelNome6;
    private javax.swing.JLabel tituloTela;
    private javax.swing.JLabel tituloTela1;
    // End of variables declaration//GEN-END:variables
}
