/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Negocio.*;
import java.util.ArrayList;
/**
 *
 * @author ANA
 */
public class TelaPrincipal extends javax.swing.JFrame {
    private ArrayList<Aluno> listaAluno = new ArrayList<>();
    private ArrayList<Responsavel> listaResponsavel = new ArrayList<>();
    private ArrayList<Modalidade> listaModalidade = new ArrayList<>();
    private ArrayList<Matricula> listaMatricula = new ArrayList<>();

    
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        menuBar2 = new java.awt.MenuBar();
        menu3 = new java.awt.Menu();
        menu4 = new java.awt.Menu();
        popupMenu1 = new java.awt.PopupMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        desktopPane = new javax.swing.JDesktopPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        menu = new javax.swing.JMenuBar();
        cadAlunoModalidaeDiaria = new javax.swing.JMenu();
        cadastroAlunoMenor = new javax.swing.JMenuItem();
        cadastroAluno = new javax.swing.JMenuItem();
        cadastroModalidadeDiaria = new javax.swing.JMenuItem();
        cadastroModalidadeLivre = new javax.swing.JMenuItem();
        acessoLogin = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        menu3.setLabel("File");
        menuBar2.add(menu3);

        menu4.setLabel("Edit");
        menuBar2.add(menu4);

        popupMenu1.setLabel("popupMenu1");

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("File");
        jMenuBar3.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar3.add(jMenu6);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Alunos matriculados em 2 modalidades", "5% desconto"},
                {"Alunos matriculados em 3 ou mais modalidades", "20% desconto"},
                {"Estudantes", "10% desconto"},
                {"Parentes(caso tenham pessoas da mesma família)", "10% desconto"},
                {null, null}
            },
            new String [] {
                "Descrição do desconto", "Percentual do desconto"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        desktopPane.add(jScrollPane1);
        jScrollPane1.setBounds(10, 60, 710, 130);

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tabela de desconto");
        desktopPane.add(jLabel1);
        jLabel1.setBounds(220, 20, 220, 28);

        menu.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                menuAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        menu.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                menuPropertyChange(evt);
            }
        });

        cadAlunoModalidaeDiaria.setMnemonic('f');
        cadAlunoModalidaeDiaria.setText("Cadastro");
        cadAlunoModalidaeDiaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadAlunoModalidaeDiariaActionPerformed(evt);
            }
        });

        cadastroAlunoMenor.setMnemonic('s');
        cadastroAlunoMenor.setText("Aluno menor de idade");
        cadastroAlunoMenor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroAlunoMenorActionPerformed(evt);
            }
        });
        cadAlunoModalidaeDiaria.add(cadastroAlunoMenor);

        cadastroAluno.setMnemonic('a');
        cadastroAluno.setText("Aluno");
        cadastroAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroAlunoActionPerformed(evt);
            }
        });
        cadAlunoModalidaeDiaria.add(cadastroAluno);

        cadastroModalidadeDiaria.setMnemonic('a');
        cadastroModalidadeDiaria.setText("Modalidade diária");
        cadastroModalidadeDiaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroModalidadeDiariaActionPerformed(evt);
            }
        });
        cadAlunoModalidaeDiaria.add(cadastroModalidadeDiaria);

        cadastroModalidadeLivre.setMnemonic('a');
        cadastroModalidadeLivre.setText("Modalidade livre");
        cadastroModalidadeLivre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroModalidadeLivreActionPerformed(evt);
            }
        });
        cadAlunoModalidaeDiaria.add(cadastroModalidadeLivre);

        menu.add(cadAlunoModalidaeDiaria);

        acessoLogin.setText("Acesso");
        acessoLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acessoLoginActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Login");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        acessoLogin.add(jMenuItem1);

        menu.add(acessoLogin);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 723, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_menuPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_menuPropertyChange

    private void cadastroAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroAlunoActionPerformed
        // TODO add your handling code here:
        TelaAluno telaAluno = new TelaAluno(listaAluno);
        telaAluno.setVisible(true);
    }//GEN-LAST:event_cadastroAlunoActionPerformed

    private void cadastroAlunoMenorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroAlunoMenorActionPerformed
        TelaAlunoMenor telaAluno = new TelaAlunoMenor(listaAluno);
        telaAluno.setVisible(true);
    }//GEN-LAST:event_cadastroAlunoMenorActionPerformed

    private void cadastroModalidadeDiariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroModalidadeDiariaActionPerformed
        // TODO add your handling code here:
        TelaModalidadeDiaria telaModalidadeDiaria = new TelaModalidadeDiaria(listaAluno,listaModalidade,listaMatricula);
        telaModalidadeDiaria.setVisible(true);
    }//GEN-LAST:event_cadastroModalidadeDiariaActionPerformed

    private void cadAlunoModalidaeDiariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadAlunoModalidaeDiariaActionPerformed
        
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cadAlunoModalidaeDiariaActionPerformed

    private void cadastroModalidadeLivreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroModalidadeLivreActionPerformed
        // TODO add your handling code here:
        TelaModalidadeLivre telaModalidadeLivre = new TelaModalidadeLivre(listaAluno,listaModalidade,listaMatricula);
        telaModalidadeLivre.setVisible(true);
    }//GEN-LAST:event_cadastroModalidadeLivreActionPerformed

    private void menuAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_menuAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_menuAncestorAdded

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        TelaLogin telaLogin = new TelaLogin(listaMatricula);
        telaLogin.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void acessoLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acessoLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acessoLoginActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu acessoLogin;
    private javax.swing.JMenu cadAlunoModalidaeDiaria;
    private javax.swing.JMenuItem cadastroAluno;
    private javax.swing.JMenuItem cadastroAlunoMenor;
    private javax.swing.JMenuItem cadastroModalidadeDiaria;
    private javax.swing.JMenuItem cadastroModalidadeLivre;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JMenuBar menu;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.Menu menu3;
    private java.awt.Menu menu4;
    private java.awt.MenuBar menuBar1;
    private java.awt.MenuBar menuBar2;
    private java.awt.PopupMenu popupMenu1;
    // End of variables declaration//GEN-END:variables

}
